ministrat.config.orbats.nato = {
  unit_103rd_reconnaissance_battalion_huzaren_van_boreel: {
    id: 'unit_103rd_reconnaissance_battalion_huzaren_van_boreel',
    name: '103rd Reconnaissance Battalion "Huzaren van Boreel"',
    type: 'armour',
    location: 'Seedorf',
  },
  unit_41_pantserbrigade: {
    id: 'unit_41_pantserbrigade',
    name: '41 Pantserbrigade',
    type: 'armour',
    location: 'Seedorf',
  },
  unit_41st_pantser_battalion_regiment_huzaren_prins_alexander: {
    id: 'unit_41st_pantser_battalion_regiment_huzaren_prins_alexander',
    name: '41st Pantser Battalion "Regiment Huzaren Prins Alexander"',
    type: 'armour',
    location: 'Bergen-Hohne',
  },
  unit_43rd_pantser_battalion_regiment_huzaren_van_sytzama: {
    id: 'unit_43rd_pantser_battalion_regiment_huzaren_van_sytzama',
    name: '43rd Pantser Battalion "Regiment Huzaren van Sytzama"',
    type: 'armour',
    location: 'Langemannshof',
  },
  unit_42nd_pantserinfanterie_battalion_regiment_limburgse_jagers: {
    id: 'unit_42nd_pantserinfanterie_battalion_regiment_limburgse_jagers',
    name: '42nd Pantserinfanterie Battalion "Regiment Limburgse Jagers"',
    type: 'armour',
    location: 'Seedorf',
  },
  unit_41st_field_artillery_battalion: {
    id: 'unit_41st_field_artillery_battalion',
    name: '41st Field Artillery Battalion',
    type: 'artillery',
    location: 'Seedorf',
  },
  unit_41st_armored_engineer_company: {
    id: 'unit_41st_armored_engineer_company',
    name: '41st Armored Engineer Company',
    type: 'armour',
    location: 'Seedorf',
  },
  unit_41st_brigade_supply_company: {
    id: 'unit_41st_brigade_supply_company',
    name: '41st Brigade Supply Company',
    type: 'infantry',
    location: 'Seedorf',
  },
  unit_41st_brigade_maintenance_company: {
    id: 'unit_41st_brigade_maintenance_company',
    name: '41st Brigade Maintenance Company',
    type: 'infantry',
    location: 'Seedorf',
  },
  unit_41st_brigade_medical_company: {
    id: 'unit_41st_brigade_medical_company',
    name: '41st Brigade Medical Company',
    type: 'infantry',
    location: 'Seedorf',
  },
  i_british_corps: {
    id: 'i_british_corps',
    name: 'I British Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_1st_br_corps_hq_defence_company: {
    id: 'unit_1st_br_corps_hq_defence_company',
    name: '1st (BR) Corps HQ Defence Company',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_1st_the_queens_dragoon_guards: {
    id: 'unit_1st_the_queens_dragoon_guards',
    name: '1st The Queen\'s Dragoon Guards',
    type: 'armour',
    location: 'Wolfenbüttel',
  },
  unit_16th_5th_queens_royal_lancers: {
    id: 'unit_16th_5th_queens_royal_lancers',
    name: '16th/5th Queen\'s Royal Lancers',
    type: 'armour',
    location: 'Herford',
  },
  unit_664_squadron_aac: {
    id: 'unit_664_squadron_aac',
    name: '664 Squadron AAC',
    type: 'air',
    location: 'Minden',
  },
  commander_royal_artillery_1_br_corps: {
    id: 'commander_royal_artillery_1_br_corps',
    name: 'Commander Royal Artillery 1 (BR) Corps',
    type: 'artillery',
    location: 'Bielefeld',
  },
  unit_1st_artillery_brigade: {
    id: 'unit_1st_artillery_brigade',
    name: '1st Artillery Brigade',
    type: 'artillery',
    location: 'Dortmund',
  },
  unit_5th_heavy_regiment_royal_artillery: {
    id: 'unit_5th_heavy_regiment_royal_artillery',
    name: '5th Heavy Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Dortmund',
  },
  unit_32nd_heavy_regiment_royal_artillery: {
    id: 'unit_32nd_heavy_regiment_royal_artillery',
    name: '32nd Heavy Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Dortmund',
  },
  corps_support_group: {
    id: 'corps_support_group',
    name: 'Corps Support Group',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_39th_heavy_regiment_royal_artillery: {
    id: 'unit_39th_heavy_regiment_royal_artillery',
    name: '39th Heavy Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Sennelager',
  },
  unit_50_missile_regiment_royal_artillery: {
    id: 'unit_50_missile_regiment_royal_artillery',
    name: '50 Missile Regiment Royal Artillery',
    type: 'artillery',
    location: 'Menden',
  },
  air_defence_group: {
    id: 'air_defence_group',
    name: 'Air Defence Group',
    type: 'air',
    location: 'Dortmund',
  },
  unit_12th_air_defence_regiment_royal_artillery: {
    id: 'unit_12th_air_defence_regiment_royal_artillery',
    name: '12th Air Defence Regiment, Royal Artillery',
    type: 'air',
    location: 'Dortmund',
  },
  unit_22nd_air_defence_regiment_royal_artillery: {
    id: 'unit_22nd_air_defence_regiment_royal_artillery',
    name: '22nd Air Defence Regiment, Royal Artillery',
    type: 'air',
    location: 'Dortmund',
  },
  unit_8th_transport_regiment_royal_corps_of_transport: {
    id: 'unit_8th_transport_regiment_royal_corps_of_transport',
    name: '8th Transport Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Münster',
  },
  commander_royal_engineers_1_br_corps: {
    id: 'commander_royal_engineers_1_br_corps',
    name: 'Commander Royal Engineers 1 (BR) Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_23rd_engineer_regiment_royal_engineers: {
    id: 'unit_23rd_engineer_regiment_royal_engineers',
    name: '23rd Engineer Regiment, Royal Engineers',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_25th_engineer_regiment_royal_engineers: {
    id: 'unit_25th_engineer_regiment_royal_engineers',
    name: '25th Engineer Regiment, Royal Engineers',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_28th_amphibious_engineer_regiment_royal_engineers: {
    id: 'unit_28th_amphibious_engineer_regiment_royal_engineers',
    name: '28th Amphibious Engineer Regiment, Royal Engineers',
    type: 'infantry',
    location: 'Hameln',
  },
  unit_32nd_armoured_engineer_regiment_royal_engineers: {
    id: 'unit_32nd_armoured_engineer_regiment_royal_engineers',
    name: '32nd Armoured Engineer Regiment, Royal Engineers',
    type: 'armour',
    location: 'Munsterlager',
  },
  unit_43rd_plant_squadron_royal_engineers: {
    id: 'unit_43rd_plant_squadron_royal_engineers',
    name: '43rd Plant Squadron, Royal Engineers',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_65th_corps_support_squadron_royal_engineers: {
    id: 'unit_65th_corps_support_squadron_royal_engineers',
    name: '65th Corps Support Squadron, Royal Engineers',
    type: 'infantry',
    location: 'Hameln',
  },
  unit_211th_mobile_civilian_artisan_group_royal_engineers: {
    id: 'unit_211th_mobile_civilian_artisan_group_royal_engineers',
    name: '211th Mobile Civilian Artisan Group, Royal Engineers',
    type: 'infantry',
    location: 'Schloss Neuhaus',
  },
  unit_256th_mobile_civilian_plant_group_royal_engineers: {
    id: 'unit_256th_mobile_civilian_plant_group_royal_engineers',
    name: '256th Mobile Civilian Plant Group, Royal Engineers',
    type: 'infantry',
    location: 'Hannover',
  },
  unit_1st_postal_and_courier_regiment_royal_engineers: {
    id: 'unit_1st_postal_and_courier_regiment_royal_engineers',
    name: '1st Postal & Courier Regiment, Royal Engineers',
    type: 'infantry',
    location: 'Hannover',
  },
  commander_aviation_baor_and_1_br_corps: {
    id: 'commander_aviation_baor_and_1_br_corps',
    name: 'Commander Aviation BAOR and 1 (BR) Corps',
    type: 'air',
    location: 'Bielefeld',
  },
  unit_1_regiment_aac: {
    id: 'unit_1_regiment_aac',
    name: '1 Regiment AAC',
    type: 'air',
    location: 'Hildesheim',
  },
  unit_3_regiment_aac: {
    id: 'unit_3_regiment_aac',
    name: '3 Regiment AAC',
    type: 'air',
    location: 'Soest',
  },
  unit_4_regiment_aac: {
    id: 'unit_4_regiment_aac',
    name: '4 Regiment AAC',
    type: 'air',
    location: 'Detmold',
  },
  commander_communications_1_br_corps: {
    id: 'commander_communications_1_br_corps',
    name: 'Commander Communications 1 (BR) Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_7th_signal_regiment_royal_signals: {
    id: 'unit_7th_signal_regiment_royal_signals',
    name: '7th Signal Regiment, Royal Signals',
    type: 'infantry',
    location: 'Herford',
  },
  unit_14th_signal_regiment_royal_signals: {
    id: 'unit_14th_signal_regiment_royal_signals',
    name: '14th Signal Regiment, Royal Signals',
    type: 'infantry',
    location: 'Celle',
  },
  unit_22nd_signal_regiment_royal_signals: {
    id: 'unit_22nd_signal_regiment_royal_signals',
    name: '22nd Signal Regiment, Royal Signals',
    type: 'infantry',
    location: 'Lippstadt',
  },
  commander_transport_1_br_corps: {
    id: 'commander_transport_1_br_corps',
    name: 'Commander Transport 1 (BR) Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_7th_tank_transporter_regiment_royal_corps_of_transport: {
    id: 'unit_7th_tank_transporter_regiment_royal_corps_of_transport',
    name: '7th Tank Transporter Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Sennelager',
  },
  unit_10th_corps_transport_regiment_royal_corps_of_transport: {
    id: 'unit_10th_corps_transport_regiment_royal_corps_of_transport',
    name: '10th Corps Transport Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_24th_transport_and_movement_regiment_royal_corps_of_transport: {
    id: 'unit_24th_transport_and_movement_regiment_royal_corps_of_transport',
    name: '24th Transport & Movement Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Hanover',
  },
  unit_25th_transport_and_movement_regiment_royal_corps_of_transport: {
    id: 'unit_25th_transport_and_movement_regiment_royal_corps_of_transport',
    name: '25th Transport & Movement Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_14th_corps_support_squadron_royal_corps_of_transport: {
    id: 'unit_14th_corps_support_squadron_royal_corps_of_transport',
    name: '14th Corps Support Squadron, Royal Corps of Transport',
    type: 'infantry',
    location: 'Bielefeld',
  },
  commander_medical_1_br_corps: {
    id: 'commander_medical_1_br_corps',
    name: 'Commander Medical 1 (BR) Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_21st_field_hospital_royal_army_medical_corps: {
    id: 'unit_21st_field_hospital_royal_army_medical_corps',
    name: '21st Field Hospital, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Rinteln',
  },
  unit_32nd_field_hospital_royal_army_medical_corps: {
    id: 'unit_32nd_field_hospital_royal_army_medical_corps',
    name: '32nd Field Hospital, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Hannover',
  },
  unit_83rd_field_medical_equipment_depot_royal_army_medical_corps: {
    id: 'unit_83rd_field_medical_equipment_depot_royal_army_medical_corps',
    name: '83rd Field Medical Equipment Depot, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Hannover',
  },
  commander_supply_1_br_corps: {
    id: 'commander_supply_1_br_corps',
    name: 'Commander Supply 1 (BR) Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_5th_ordnance_battalion_royal_army_ordnance_corps: {
    id: 'unit_5th_ordnance_battalion_royal_army_ordnance_corps',
    name: '5th Ordnance Battalion, Royal Army Ordnance Corps',
    type: 'infantry',
    location: 'Paderborn',
  },
  unit_6th_ordnance_battalion_royal_army_ordnance_corps: {
    id: 'unit_6th_ordnance_battalion_royal_army_ordnance_corps',
    name: '6th Ordnance Battalion, Royal Army Ordnance Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_2nd_aircraft_support_unit_royal_army_ordnance_corps: {
    id: 'unit_2nd_aircraft_support_unit_royal_army_ordnance_corps',
    name: '2nd Aircraft Support Unit, Royal Army Ordnance Corps',
    type: 'air',
    location: 'Detmold',
  },
  commander_maintenance_1_br_corps: {
    id: 'commander_maintenance_1_br_corps',
    name: 'Commander Maintenance 1 (BR) Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_1st_br_corps_troops_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_1st_br_corps_troops_workshop_royal_electrical_and_mechanical_engineers',
    name: '1st (BR) Corps Troops Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_20th_electronics_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_20th_electronics_workshop_royal_electrical_and_mechanical_engineers',
    name: '20th Electronics Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Minden',
  },
  unit_71st_aircraft_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_71st_aircraft_workshop_royal_electrical_and_mechanical_engineers',
    name: '71st Aircraft Workshop, Royal Electrical and Mechanical Engineers',
    type: 'air',
    location: 'Detmold',
  },
  provost_marshal_1_br_corps: {
    id: 'provost_marshal_1_br_corps',
    name: 'Provost Marshal 1 (BR) Corps',
    type: 'infantry',
    location: 'Bielefeld',
  },
  unit_110th_provost_company_royal_military_police: {
    id: 'unit_110th_provost_company_royal_military_police',
    name: '110th Provost Company, Royal Military Police',
    type: 'infantry',
    location: 'Sennelager',
  },
  unit_115th_provost_company_royal_military_police: {
    id: 'unit_115th_provost_company_royal_military_police',
    name: '115th Provost Company, Royal Military Police',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_1st_armoured_division: {
    id: 'unit_1st_armoured_division',
    name: '1st Armoured Division',
    type: 'armour',
    location: 'Verden',
  },
  hq_1st_armoured_division_and_signal_regiment_royal_signals: {
    id: 'hq_1st_armoured_division_and_signal_regiment_royal_signals',
    name: 'HQ 1st Armoured Division & Signal Regiment, Royal Signals',
    type: 'armour',
    location: 'Verden',
  },
  unit_7th_armoured_brigade: {
    id: 'unit_7th_armoured_brigade',
    name: '7th Armoured Brigade',
    type: 'armour',
    location: 'Soltau',
  },
  royal_scots_dragoon_guards: {
    id: 'royal_scots_dragoon_guards',
    name: 'Royal Scots Dragoon Guards',
    type: 'armour',
    location: 'Fallingbostel',
  },
  unit_2nd_royal_tank_regiment: {
    id: 'unit_2nd_royal_tank_regiment',
    name: '2nd Royal Tank Regiment',
    type: 'armour',
    location: 'Fallingbostel',
  },
  unit_1st_btn_staffordshire_regiment: {
    id: 'unit_1st_btn_staffordshire_regiment',
    name: '1st Btn, Staffordshire Regiment',
    type: 'infantry',
    location: 'Fallingbostel',
  },
  unit_12th_armoured_brigade: {
    id: 'unit_12th_armoured_brigade',
    name: '12th Armoured Brigade',
    type: 'armour',
    location: 'Osnabrück',
  },
  unit_4th_royal_tank_regiment: {
    id: 'unit_4th_royal_tank_regiment',
    name: '4th Royal Tank Regiment',
    type: 'armour',
    location: 'Osnabrück',
  },
  unit_1st_btn_royal_irish_rangers: {
    id: 'unit_1st_btn_royal_irish_rangers',
    name: '1st Btn, Royal Irish Rangers',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_1st_btn_royal_green_jackets: {
    id: 'unit_1st_btn_royal_green_jackets',
    name: '1st Btn, Royal Green Jackets',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_22nd_armoured_brigade: {
    id: 'unit_22nd_armoured_brigade',
    name: '22nd Armoured Brigade',
    type: 'armour',
    location: 'Bergen-Hohne',
  },
  queens_own_hussars: {
    id: 'queens_own_hussars',
    name: 'Queen\'s Own Hussars',
    type: 'armour',
    location: 'Bergen-Hohne',
  },
  unit_1st_royal_tank_regiment: {
    id: 'unit_1st_royal_tank_regiment',
    name: '1st Royal Tank Regiment',
    type: 'armour',
    location: 'Hildesheim',
  },
  unit_1st_btn_scots_guards: {
    id: 'unit_1st_btn_scots_guards',
    name: '1st Btn, Scots Guards',
    type: 'infantry',
    location: 'Bergen-Hohne',
  },
  unit_2nd_btn_royal_anglian_regiment: {
    id: 'unit_2nd_btn_royal_anglian_regiment',
    name: '2nd Btn, Royal Anglian Regiment',
    type: 'infantry',
    location: 'Celle',
  },
  unit_1st_field_regiment_royal_horse_artillery: {
    id: 'unit_1st_field_regiment_royal_horse_artillery',
    name: '1st Field Regiment, Royal Horse Artillery',
    type: 'artillery',
    location: 'Bergen-Hohne',
  },
  unit_4th_field_regiment_royal_artillery: {
    id: 'unit_4th_field_regiment_royal_artillery',
    name: '4th Field Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Osnabrück',
  },
  unit_40th_field_regiment_royal_artillery: {
    id: 'unit_40th_field_regiment_royal_artillery',
    name: '40th Field Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Bergen-Hohne',
  },
  unit_21st_engineer_regiment_royal_engineers: {
    id: 'unit_21st_engineer_regiment_royal_engineers',
    name: '21st Engineer Regiment, Royal Engineers',
    type: 'infantry',
    location: 'Nienburg',
  },
  unit_1st_armoured_division_transport_regiment_royal_corps_of_transport: {
    id: 'unit_1st_armoured_division_transport_regiment_royal_corps_of_transport',
    name: '1st Armoured Division Transport Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Bunde',
  },
  unit_1st_ordnance_battalion_royal_army_ordnance_corps: {
    id: 'unit_1st_ordnance_battalion_royal_army_ordnance_corps',
    name: '1st Ordnance Battalion, Royal Army Ordnance Corps',
    type: 'infantry',
    location: 'Verden',
  },
  unit_7th_armoured_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_7th_armoured_workshop_royal_electrical_and_mechanical_engineers',
    name: '7th Armoured Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Fallingbostel',
  },
  unit_12th_armoured_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_12th_armoured_workshop_royal_electrical_and_mechanical_engineers',
    name: '12th Armoured Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_1st_armoured_field_ambulance_royal_army_medical_corps: {
    id: 'unit_1st_armoured_field_ambulance_royal_army_medical_corps',
    name: '1st Armoured Field Ambulance, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Bergen-Hohne',
  },
  unit_2nd_armoured_field_ambulance_royal_army_medical_corps: {
    id: 'unit_2nd_armoured_field_ambulance_royal_army_medical_corps',
    name: '2nd Armoured Field Ambulance, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Osnabrück',
  },
  unit_111th_provost_company_royal_military_police: {
    id: 'unit_111th_provost_company_royal_military_police',
    name: '111th Provost Company, Royal Military Police',
    type: 'infantry',
    location: 'Bergen-Hohne',
  },
  unit_3rd_armoured_division: {
    id: 'unit_3rd_armoured_division',
    name: '3rd Armoured Division',
    type: 'armour',
    location: 'Soest',
  },
  hq_3rd_armoured_division_and_signal_regiment_royal_signals: {
    id: 'hq_3rd_armoured_division_and_signal_regiment_royal_signals',
    name: 'HQ 3rd Armoured Division & Signal Regiment, Royal Signals',
    type: 'armour',
    location: 'Soest',
  },
  unit_4th_armoured_brigade: {
    id: 'unit_4th_armoured_brigade',
    name: '4th Armoured Brigade',
    type: 'armour',
    location: 'Münster',
  },
  unit_14th_20th_kings_hussars: {
    id: 'unit_14th_20th_kings_hussars',
    name: '14th/20th King\'s Hussars',
    type: 'armour',
    location: 'Münster',
  },
  unit_17th_21st_lancers: {
    id: 'unit_17th_21st_lancers',
    name: '17th/21st Lancers',
    type: 'armour',
    location: 'Münster',
  },
  unit_1st_btn_grenadier_guards: {
    id: 'unit_1st_btn_grenadier_guards',
    name: '1st Btn, Grenadier Guards',
    type: 'infantry',
    location: 'Münster',
  },
  unit_6th_armoured_brigade: {
    id: 'unit_6th_armoured_brigade',
    name: '6th Armoured Brigade',
    type: 'armour',
    location: 'Soest',
  },
  unit_3rd_royal_tank_regiment: {
    id: 'unit_3rd_royal_tank_regiment',
    name: '3rd Royal Tank Regiment',
    type: 'armour',
    location: 'Hemer',
  },
  unit_1st_btn_royal_scots: {
    id: 'unit_1st_btn_royal_scots',
    name: '1st Btn, Royal Scots',
    type: 'infantry',
    location: 'Werl',
  },
  unit_3rd_btn_royal_regiment_of_fusiliers: {
    id: 'unit_3rd_btn_royal_regiment_of_fusiliers',
    name: '3rd Btn, Royal Regiment of Fusiliers',
    type: 'infantry',
    location: 'Hemer',
  },
  unit_33rd_armoured_brigade: {
    id: 'unit_33rd_armoured_brigade',
    name: '33rd Armoured Brigade',
    type: 'armour',
    location: 'Paderborn',
  },
  blues_and_royals: {
    id: 'blues_and_royals',
    name: 'Blues and Royals',
    type: 'armour',
    location: 'Sennelager',
  },
  unit_1st_btn_queens_own_highlanders: {
    id: 'unit_1st_btn_queens_own_highlanders',
    name: '1st Btn, Queen\'s Own Highlanders',
    type: 'infantry',
    location: 'Münster',
  },
  unit_1st_btn_queens_lancashire_regiment: {
    id: 'unit_1st_btn_queens_lancashire_regiment',
    name: '1st Btn, Queen\'s Lancashire Regiment',
    type: 'infantry',
    location: 'Paderborn',
  },
  unit_2nd_field_regiment_royal_artillery: {
    id: 'unit_2nd_field_regiment_royal_artillery',
    name: '2nd Field Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Münster',
  },
  unit_3rd_field_regiment_royal_horse_artillery: {
    id: 'unit_3rd_field_regiment_royal_horse_artillery',
    name: '3rd Field Regiment, Royal Horse Artillery',
    type: 'artillery',
    location: 'Paderborn',
  },
  unit_49th_field_regiment_royal_artillery: {
    id: 'unit_49th_field_regiment_royal_artillery',
    name: '49th Field Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Lippstadt',
  },
  unit_26th_engineer_regiment_royal_engineers: {
    id: 'unit_26th_engineer_regiment_royal_engineers',
    name: '26th Engineer Regiment, Royal Engineers',
    type: 'infantry',
    location: 'Iserlohn',
  },
  unit_3rd_armoured_division_transport_regiment_royal_corps_of_transport: {
    id: 'unit_3rd_armoured_division_transport_regiment_royal_corps_of_transport',
    name: '3rd Armoured Division Transport Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Duisburg',
  },
  unit_3rd_ordnance_battalion_royal_army_ordnance_corps: {
    id: 'unit_3rd_ordnance_battalion_royal_army_ordnance_corps',
    name: '3rd Ordnance Battalion, Royal Army Ordnance Corps',
    type: 'infantry',
    location: 'Soest',
  },
  unit_5th_armoured_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_5th_armoured_workshop_royal_electrical_and_mechanical_engineers',
    name: '5th Armoured Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Soest',
  },
  unit_6th_armoured_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_6th_armoured_workshop_royal_electrical_and_mechanical_engineers',
    name: '6th Armoured Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Münster',
  },
  unit_11th_armoured_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_11th_armoured_workshop_royal_electrical_and_mechanical_engineers',
    name: '11th Armoured Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Soest',
  },
  unit_3rd_armoured_field_ambulance_royal_army_medical_corps: {
    id: 'unit_3rd_armoured_field_ambulance_royal_army_medical_corps',
    name: '3rd Armoured Field Ambulance, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Sennelager',
  },
  unit_5th_armoured_field_ambulance_royal_army_medical_corps: {
    id: 'unit_5th_armoured_field_ambulance_royal_army_medical_corps',
    name: '5th Armoured Field Ambulance, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Münster',
  },
  unit_113th_provost_company_royal_military_police: {
    id: 'unit_113th_provost_company_royal_military_police',
    name: '113th Provost Company, Royal Military Police',
    type: 'infantry',
    location: 'Werl',
  },
  unit_4th_armoured_division: {
    id: 'unit_4th_armoured_division',
    name: '4th Armoured Division',
    type: 'armour',
    location: 'Herford',
  },
  hq_4th_armoured_division_and_signal_regiment_royal_signals: {
    id: 'hq_4th_armoured_division_and_signal_regiment_royal_signals',
    name: 'HQ 4th Armoured Division & Signal Regiment, Royal Signals',
    type: 'armour',
    location: 'Herford',
  },
  unit_11th_armoured_brigade: {
    id: 'unit_11th_armoured_brigade',
    name: '11th Armoured Brigade',
    type: 'armour',
    location: 'Minden',
  },
  unit_5th_royal_inniskilling_dragoon_guards: {
    id: 'unit_5th_royal_inniskilling_dragoon_guards',
    name: '5th Royal Inniskilling Dragoon Guards',
    type: 'armour',
    location: 'Paderborn',
  },
  unit_1st_btn_argyll_and_sutherland_highlanders: {
    id: 'unit_1st_btn_argyll_and_sutherland_highlanders',
    name: '1st Btn, Argyll and Sutherland highlanders',
    type: 'infantry',
    location: 'Minden',
  },
  unit_2nd_btn_queens_regiment: {
    id: 'unit_2nd_btn_queens_regiment',
    name: '2nd Btn, Queen\'s Regiment',
    type: 'infantry',
    location: 'Minden',
  },
  unit_20th_armoured_brigade: {
    id: 'unit_20th_armoured_brigade',
    name: '20th Armoured Brigade',
    type: 'armour',
    location: 'Detmold',
  },
  unit_4th_7th_royal_dragoon_guards: {
    id: 'unit_4th_7th_royal_dragoon_guards',
    name: '4th/7th Royal Dragoon Guards',
    type: 'armour',
    location: 'Detmold',
  },
  unit_15th_19th_kings_royal_hussars: {
    id: 'unit_15th_19th_kings_royal_hussars',
    name: '15th/19th King\'s Royal Hussars',
    type: 'armour',
    location: 'Detmold',
  },
  unit_2nd_btn_royal_irish_rangers: {
    id: 'unit_2nd_btn_royal_irish_rangers',
    name: '2nd Btn, Royal Irish Rangers',
    type: 'infantry',
    location: 'Lemgo',
  },
  unit_19th_field_regiment_royal_artillery: {
    id: 'unit_19th_field_regiment_royal_artillery',
    name: '19th Field Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Dortmund',
  },
  unit_26th_field_regiment_royal_artillery: {
    id: 'unit_26th_field_regiment_royal_artillery',
    name: '26th Field Regiment, Royal Artillery',
    type: 'artillery',
    location: 'Gütersloh',
  },
  unit_35th_engineer_regiment_royal_engineers: {
    id: 'unit_35th_engineer_regiment_royal_engineers',
    name: '35th Engineer Regiment, Royal Engineers',
    type: 'infantry',
    location: 'Hamlen',
  },
  unit_4th_armoured_division_transport_regiment_royal_corps_of_transport: {
    id: 'unit_4th_armoured_division_transport_regiment_royal_corps_of_transport',
    name: '4th Armoured Division Transport Regiment, Royal Corps of Transport',
    type: 'infantry',
    location: 'Minden',
  },
  unit_4th_ordnance_battalion_royal_army_ordnance_corps: {
    id: 'unit_4th_ordnance_battalion_royal_army_ordnance_corps',
    name: '4th Ordnance Battalion, Royal Army Ordnance Corps',
    type: 'infantry',
    location: 'Herford',
  },
  unit_4th_armoured_workshop_royal_electrical_and_mechanical_engineers: {
    id: 'unit_4th_armoured_workshop_royal_electrical_and_mechanical_engineers',
    name: '4th Armoured Workshop, Royal Electrical and Mechanical Engineers',
    type: 'infantry',
    location: 'Detmold',
  },
  unit_4th_armoured_field_ambulance_royal_army_medical_corps: {
    id: 'unit_4th_armoured_field_ambulance_royal_army_medical_corps',
    name: '4th Armoured Field Ambulance, Royal Army Medical Corps',
    type: 'infantry',
    location: 'Minden',
  },
  unit_114th_provost_company_royal_military_police: {
    id: 'unit_114th_provost_company_royal_military_police',
    name: '114th Provost Company, Royal Military Police',
    type: 'infantry',
    location: 'Detmold',
  },
  corps_reconnaissance_command: {
    id: 'corps_reconnaissance_command',
    name: 'Corps Reconnaissance Command',
    type: 'armour',
    location: 'Arolsen',
  },
  unit_1ste_jagers_te_paard: {
    id: 'unit_1ste_jagers_te_paard',
    name: '1ste Jagers te Paard',
    type: 'armour',
    location: 'Arolsen',
  },
  unit_2de_jagers_te_paard: {
    id: 'unit_2de_jagers_te_paard',
    name: '2de Jagers te Paard',
    type: 'armour',
    location: 'Lüdenscheid',
  },
  unit_4e_chasseurs_a_cheval: {
    id: 'unit_4e_chasseurs_a_cheval',
    name: '4e Chasseurs à Cheval',
    type: 'armour',
    location: 'Arnsberg',
  },
  unit_1er_compagnie_dequipes_speciales_de_reconnaissance: {
    id: 'unit_1er_compagnie_dequipes_speciales_de_reconnaissance',
    name: '1er Compagnie d\'Equipes Spéciales de Reconnaissance',
    type: 'infantry',
    location: 'Troisdorf',
  },
  unit_210th_logistic_company: {
    id: 'unit_210th_logistic_company',
    name: '210th Logistic Company',
    type: 'infantry',
    location: 'Arolsen',
  },
  corps_artillery_command: {
    id: 'corps_artillery_command',
    name: 'Corps Artillery Command',
    type: 'artillery',
    location: 'Cologne',
  },
  unit_3rd_artillery_regiment: {
    id: 'unit_3rd_artillery_regiment',
    name: '3rd Artillery Regiment',
    type: 'artillery',
    location: 'Werl',
  },
  unit_13th_artillery_regiment: {
    id: 'unit_13th_artillery_regiment',
    name: '13th Artillery Regiment',
    type: 'artillery',
    location: 'Büren',
  },
  unit_14th_anti_air_artillery_battalion: {
    id: 'unit_14th_anti_air_artillery_battalion',
    name: '14th Anti-Air Artillery Battalion',
    type: 'air',
    location: 'Spich',
  },
  unit_17th_horse_artillery_regiment: {
    id: 'unit_17th_horse_artillery_regiment',
    name: '17th Horse Artillery Regiment',
    type: 'artillery',
    location: 'Altenrath',
  },
  unit_18th_artillery_regiment: {
    id: 'unit_18th_artillery_regiment',
    name: '18th Artillery Regiment',
    type: 'artillery',
    location: 'Brasschaat',
  },
  unit_20th_artillery_regiment: {
    id: 'unit_20th_artillery_regiment',
    name: '20th Artillery Regiment',
    type: 'artillery',
    location: 'Werl',
  },
  unit_35th_anti_air_artillery_battalion: {
    id: 'unit_35th_anti_air_artillery_battalion',
    name: '35th Anti-Air Artillery Battalion',
    type: 'air',
    location: 'Spich',
  },
  unit_73rd_special_ammunition_battery: {
    id: 'unit_73rd_special_ammunition_battery',
    name: '73rd Special Ammunition Battery',
    type: 'artillery',
    location: 'Soest',
  },
  unit_80th_observation_and_surveillance_battery: {
    id: 'unit_80th_observation_and_surveillance_battery',
    name: '80th Observation and Surveillance Battery',
    type: 'artillery',
    location: 'Cologne',
  },
  unit_95th_hawk_and_lance_maintenance_battery: {
    id: 'unit_95th_hawk_and_lance_maintenance_battery',
    name: '95th Hawk and Lance Maintenance Battery',
    type: 'artillery',
    location: 'Werl',
  },
  unit_1st_light_aviation_group: {
    id: 'unit_1st_light_aviation_group',
    name: '1st Light Aviation Group',
    type: 'air',
    location: 'Cologne',
  },
  unit_16th_light_aviation_squadron: {
    id: 'unit_16th_light_aviation_squadron',
    name: '16th Light Aviation Squadron',
    type: 'air',
    location: 'Cologne',
  },
  unit_17th_light_aviation_squadron: {
    id: 'unit_17th_light_aviation_squadron',
    name: '17th Light Aviation Squadron',
    type: 'air',
    location: 'Werl',
  },
  unit_18th_light_aviation_squadron: {
    id: 'unit_18th_light_aviation_squadron',
    name: '18th Light Aviation Squadron',
    type: 'air',
    location: 'Merzbrück',
  },
  unit_1st_engineer_group: {
    id: 'unit_1st_engineer_group',
    name: '1st Engineer Group',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_1st_engineer_regiment: {
    id: 'unit_1st_engineer_regiment',
    name: '1st Engineer Regiment',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_3rd_bridge_engineer_regiment: {
    id: 'unit_3rd_bridge_engineer_regiment',
    name: '3rd Bridge Engineer Regiment',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_6th_engineer_regiment: {
    id: 'unit_6th_engineer_regiment',
    name: '6th Engineer Regiment',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_10th_field_engineer_regiment: {
    id: 'unit_10th_field_engineer_regiment',
    name: '10th Field Engineer Regiment',
    type: 'infantry',
    location: 'Amay',
  },
  unit_17th_field_engineer_regiment: {
    id: 'unit_17th_field_engineer_regiment',
    name: '17th Field Engineer Regiment',
    type: 'infantry',
    location: 'Zwijndrecht',
  },
  topography_and_geography_company: {
    id: 'topography_and_geography_company',
    name: 'Topography and Geography Company',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_1st_signal_group: {
    id: 'unit_1st_signal_group',
    name: '1st Signal Group',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_4th_signal_battalion: {
    id: 'unit_4th_signal_battalion',
    name: '4th Signal Battalion',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_6th_signal_battalion: {
    id: 'unit_6th_signal_battalion',
    name: '6th Signal Battalion',
    type: 'infantry',
    location: 'Lüdenscheid',
  },
  unit_13th_signal_company: {
    id: 'unit_13th_signal_company',
    name: '13th Signal Company',
    type: 'infantry',
    location: 'Krefeld',
  },
  unit_17th_signal_company: {
    id: 'unit_17th_signal_company',
    name: '17th Signal Company',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_20th_signal_company: {
    id: 'unit_20th_signal_company',
    name: '20th Signal Company',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_4th_logistic_battalion: {
    id: 'unit_4th_logistic_battalion',
    name: '4th Logistic Battalion',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_18th_logistic_battalion: {
    id: 'unit_18th_logistic_battalion',
    name: '18th Logistic Battalion',
    type: 'infantry',
    location: 'Lüdenscheid',
  },
  unit_20th_logistic_battalion: {
    id: 'unit_20th_logistic_battalion',
    name: '20th Logistic Battalion',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_29th_logistic_battalion: {
    id: 'unit_29th_logistic_battalion',
    name: '29th Logistic Battalion',
    type: 'infantry',
    location: 'Eschweiler',
  },
  unit_51st_logistic_battalion: {
    id: 'unit_51st_logistic_battalion',
    name: '51st Logistic Battalion',
    type: 'infantry',
    location: 'Aachen',
  },
  unit_2nd_military_police_company: {
    id: 'unit_2nd_military_police_company',
    name: '2nd Military Police Company',
    type: 'infantry',
    location: 'Arnsberg',
  },
  unit_6th_military_police_company: {
    id: 'unit_6th_military_police_company',
    name: '6th Military Police Company',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_7th_military_police_company: {
    id: 'unit_7th_military_police_company',
    name: '7th Military Police Company',
    type: 'infantry',
    location: 'Liège',
  },
  unit_1st_ambulance_company: {
    id: 'unit_1st_ambulance_company',
    name: '1st Ambulance Company',
    type: 'infantry',
    location: 'Soest',
  },
  unit_2nd_ambulance_company: {
    id: 'unit_2nd_ambulance_company',
    name: '2nd Ambulance Company',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_3rd_ambulance_company: {
    id: 'unit_3rd_ambulance_company',
    name: '3rd Ambulance Company',
    type: 'infantry',
    location: 'Cologne',
  },
  unit_16de_pantserdivisie: {
    id: 'unit_16de_pantserdivisie',
    name: '16de Pantserdivisie',
    type: 'armour',
    location: 'Neheim-Hüsten',
  },
  unit_4de_pantserinfanteriebrigade: {
    id: 'unit_4de_pantserinfanteriebrigade',
    name: '4de Pantserinfanteriebrigade',
    type: 'armour',
    location: 'Soest',
  },
  unit_4de_regiment_lansiers: {
    id: 'unit_4de_regiment_lansiers',
    name: '4de Regiment Lansiers',
    type: 'armour',
    location: 'Soest',
  },
  unit_1ste_regiment_grenadiers: {
    id: 'unit_1ste_regiment_grenadiers',
    name: '1ste Regiment Grenadiers',
    type: 'infantry',
    location: 'Soest',
  },
  unit_5de_linieregiment: {
    id: 'unit_5de_linieregiment',
    name: '5de Linieregiment',
    type: 'infantry',
    location: 'Soest',
  },
  unit_6de_regiment_artillerie: {
    id: 'unit_6de_regiment_artillerie',
    name: '6de Regiment Artillerie',
    type: 'artillery',
    location: 'Soest',
  },
  unit_17eme_brigade_blindee: {
    id: 'unit_17eme_brigade_blindee',
    name: '17ème Brigade Blindée',
    type: 'armour',
    location: 'Siegen',
  },
  unit_1er_regiment_des_guides: {
    id: 'unit_1er_regiment_des_guides',
    name: '1er Régiment des Guides',
    type: 'armour',
    location: 'Siegen',
  },
  unit_2e_regiment_gidsen: {
    id: 'unit_2e_regiment_gidsen',
    name: '2e Regiment Gidsen',
    type: 'armour',
    location: 'Altenrath',
  },
  unit_1ste_regiment_karabiniers_wielrijders: {
    id: 'unit_1ste_regiment_karabiniers_wielrijders',
    name: '1ste Regiment Karabiniers Wielrijders',
    type: 'infantry',
    location: 'Spich',
  },
  unit_2eme_regiment_de_carabiniers_cyclistes: {
    id: 'unit_2eme_regiment_de_carabiniers_cyclistes',
    name: '2ème Régiment de Carabiniers-cyclistes',
    type: 'infantry',
    location: 'Siegen',
  },
  unit_19e_regiment_dartillerie_a_cheval: {
    id: 'unit_19e_regiment_dartillerie_a_cheval',
    name: '19e Régiment d\'Artillerie à Cheval',
    type: 'artillery',
    location: 'Siegen',
  },
  unit_5th_personnel_group: {
    id: 'unit_5th_personnel_group',
    name: '5th Personnel Group',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_5th_finance_group: {
    id: 'unit_5th_finance_group',
    name: '5th Finance Group',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_4th_battalion_2nd_air_defense_artillery: {
    id: 'unit_4th_battalion_2nd_air_defense_artillery',
    name: '4th Battalion, 2nd Air Defense Artillery',
    type: 'air',
    location: 'Giessen',
  },
  unit_12th_aviation_brigade: {
    id: 'unit_12th_aviation_brigade',
    name: '12th Aviation Brigade',
    type: 'air',
    location: 'Wiesbaden',
  },
  unit_5th_squadron_6th_cavalry: {
    id: 'unit_5th_squadron_6th_cavalry',
    name: '5th Squadron, 6th Cavalry',
    type: 'armour',
    location: '', // Location was '(location not specified)'
  },
  unit_5th_battalion_158th_aviation: {
    id: 'unit_5th_battalion_158th_aviation',
    name: '5th Battalion, 158th Aviation',
    type: 'air',
    location: 'Frankfurt-Bonames',
  },
  unit_6th_battalion_229th_aviation: {
    id: 'unit_6th_battalion_229th_aviation',
    name: '6th Battalion, 229th Aviation',
    type: 'air',
    location: '', // Location was '(location not specified)'
  },
  unit_130th_engineer_brigade: {
    id: 'unit_130th_engineer_brigade',
    name: '130th Engineer Brigade',
    type: 'infantry',
    location: 'Hanau',
  },
  unit_54th_engineer_battalion: {
    id: 'unit_54th_engineer_battalion',
    name: '54th Engineer Battalion',
    type: 'infantry',
    location: '', // Location was '(location not specified)'
  },
  unit_317th_engineer_battalion: {
    id: 'unit_317th_engineer_battalion',
    name: '317th Engineer Battalion',
    type: 'infantry',
    location: '', // Location was '(location not specified)'
  },
  unit_547th_engineer_battalion: {
    id: 'unit_547th_engineer_battalion',
    name: '547th Engineer Battalion',
    type: 'infantry',
    location: '', // Location was '(location not specified)'
  },
  unit_559th_engineer_battalion: {
    id: 'unit_559th_engineer_battalion',
    name: '559th Engineer Battalion',
    type: 'infantry',
    location: '', // Location was '(location not specified)'
  },
  unit_18th_military_police_brigade: {
    id: 'unit_18th_military_police_brigade',
    name: '18th Military Police Brigade',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_93rd_military_police_battalion: {
    id: 'unit_93rd_military_police_battalion',
    name: '93rd Military Police Battalion',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_709th_military_police_battalion: {
    id: 'unit_709th_military_police_battalion',
    name: '709th Military Police Battalion',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_22nd_signal_brigade: {
    id: 'unit_22nd_signal_brigade',
    name: '22nd Signal Brigade',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_17th_signal_battalion: {
    id: 'unit_17th_signal_battalion',
    name: '17th Signal Battalion',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_32nd_signal_battalion: {
    id: 'unit_32nd_signal_battalion',
    name: '32nd Signal Battalion',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_44th_signal_battalion: {
    id: 'unit_44th_signal_battalion',
    name: '44th Signal Battalion',
    type: 'infantry',
    location: 'Darmstadt',
  },
  unit_205th_military_intelligence_brigade: {
    id: 'unit_205th_military_intelligence_brigade',
    name: '205th Military Intelligence Brigade',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_1st_military_intelligence_battalion: {
    id: 'unit_1st_military_intelligence_battalion',
    name: '1st Military Intelligence Battalion',
    type: 'infantry',
    location: 'Wiesbaden',
  },
  unit_165th_military_intelligence_battalion: {
    id: 'unit_165th_military_intelligence_battalion',
    name: '165th Military Intelligence Battalion',
    type: 'infantry',
    location: 'Darmstadt',
  },
  unit_302nd_military_intelligence_battalion: {
    id: 'unit_302nd_military_intelligence_battalion',
    name: '302nd Military Intelligence Battalion',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_3rd_armored_division_2: { // Duplicate key: unit_3rd_armoured_division (UK) exists
    id: 'unit_3rd_armored_division_2',
    name: '3rd Armored Division',
    type: 'armour',
    location: 'Frankfurt',
  },
  unit_1st_brigade: {
    id: 'unit_1st_brigade',
    name: '1st Brigade',
    type: 'armour',
    location: 'Kirch-Göns',
  },
  unit_2nd_battalion_32nd_armor: {
    id: 'unit_2nd_battalion_32nd_armor',
    name: '2nd Battalion, 32nd Armor',
    type: 'armour',
    location: 'Kirch-Göns',
  },
  unit_4th_battalion_32nd_armor: {
    id: 'unit_4th_battalion_32nd_armor',
    name: '4th Battalion, 32nd Armor',
    type: 'armour',
    location: 'Kirch-Göns',
  },
  unit_3rd_squadron_5th_cavalry: {
    id: 'unit_3rd_squadron_5th_cavalry',
    name: '3rd Squadron, 5th Cavalry',
    type: 'armour',
    location: 'Kirch-Göns',
  },
  unit_5th_squadron_5th_cavalry: {
    id: 'unit_5th_squadron_5th_cavalry',
    name: '5th Squadron, 5th Cavalry',
    type: 'armour',
    location: 'Kirch-Göns',
  },
  unit_2nd_brigade: {
    id: 'unit_2nd_brigade',
    name: '2nd Brigade',
    type: 'armour',
    location: 'Gelnhausen',
  },
  unit_3rd_squadron_8th_cavalry: {
    id: 'unit_3rd_squadron_8th_cavalry',
    name: '3rd Squadron, 8th Cavalry',
    type: 'armour',
    location: 'Gelnhausen',
  },
  unit_4th_squadron_8th_cavalry: {
    id: 'unit_4th_squadron_8th_cavalry',
    name: '4th Squadron, 8th Cavalry',
    type: 'armour',
    location: 'Gelnhausen',
  },
  unit_4th_battalion_18th_infantry: {
    id: 'unit_4th_battalion_18th_infantry',
    name: '4th Battalion, 18th Infantry',
    type: 'infantry',
    location: 'Gelnhausen',
  },
  unit_3rd_brigade: {
    id: 'unit_3rd_brigade',
    name: '3rd Brigade',
    type: 'armour',
    location: 'Friedberg',
  },
  unit_2nd_battalion_67th_armor: {
    id: 'unit_2nd_battalion_67th_armor',
    name: '2nd Battalion, 67th Armor',
    type: 'armour',
    location: 'Friedberg',
  },
  unit_4th_battalion_67th_armor: {
    id: 'unit_4th_battalion_67th_armor',
    name: '4th Battalion, 67th Armor',
    type: 'armour',
    location: 'Friedberg',
  },
  unit_5th_battalion_18th_infantry: {
    id: 'unit_5th_battalion_18th_infantry',
    name: '5th Battalion, 18th Infantry',
    type: 'infantry',
    location: 'Friedberg',
  },
  unit_4th_brigade_aviation: {
    id: 'unit_4th_brigade_aviation',
    name: '4th Brigade (Aviation)',
    type: 'air',
    location: 'Hanau',
  },
  unit_4th_squadron_7th_cavalry: {
    id: 'unit_4th_squadron_7th_cavalry',
    name: '4th Squadron, 7th Cavalry',
    type: 'air',
    location: 'Büdingen',
  },
  unit_2nd_battalion_227th_aviation: {
    id: 'unit_2nd_battalion_227th_aviation',
    name: '2nd Battalion, 227th Aviation',
    type: 'air',
    location: '', // Location was '(location not specified)'
  },
  unit_3rd_battalion_227th_aviation: {
    id: 'unit_3rd_battalion_227th_aviation',
    name: '3rd Battalion, 227th Aviation',
    type: 'air',
    location: '', // Location was '(location not specified)'
  },
  unit_3rd_armored_division_artillery: {
    id: 'unit_3rd_armored_division_artillery',
    name: '3rd Armored Division Artillery',
    type: 'artillery',
    location: 'Hanau',
  },
  unit_2nd_battalion_3rd_field_artillery: {
    id: 'unit_2nd_battalion_3rd_field_artillery',
    name: '2nd Battalion, 3rd Field Artillery',
    type: 'artillery',
    location: 'Kirch-Göns',
  },
  unit_2nd_battalion_82nd_field_artillery: {
    id: 'unit_2nd_battalion_82nd_field_artillery',
    name: '2nd Battalion, 82nd Field Artillery',
    type: 'artillery',
    location: 'Friedberg',
  },
  unit_4th_battalion_82nd_field_artillery: {
    id: 'unit_4th_battalion_82nd_field_artillery',
    name: '4th Battalion, 82nd Field Artillery',
    type: 'artillery',
    location: 'Hanau',
  },
  unit_3rd_armored_division_support_command: {
    id: 'unit_3rd_armored_division_support_command',
    name: '3rd Armored Division Support Command',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_45th_support_battalion: {
    id: 'unit_45th_support_battalion',
    name: '45th Support Battalion',
    type: 'infantry',
    location: 'Gelnhausen',
  },
  unit_54th_support_battalion: {
    id: 'unit_54th_support_battalion',
    name: '54th Support Battalion',
    type: 'infantry',
    location: 'Friedberg',
  },
  unit_122nd_support_battalion: {
    id: 'unit_122nd_support_battalion',
    name: '122nd Support Battalion',
    type: 'infantry',
    location: 'Hanau',
  },
  unit_503rd_support_battalion: {
    id: 'unit_503rd_support_battalion',
    name: '503rd Support Battalion',
    type: 'infantry',
    location: 'Kirchgoens',
  },
  unit_3rd_battalion_5th_air_defense_artillery: {
    id: 'unit_3rd_battalion_5th_air_defense_artillery',
    name: '3rd Battalion, 5th Air Defense Artillery',
    type: 'air',
    location: 'Büdingen',
  },
  unit_23rd_engineer_battalion: {
    id: 'unit_23rd_engineer_battalion',
    name: '23rd Engineer Battalion',
    type: 'infantry',
    location: 'Hanau',
  },
  unit_143rd_signal_battalion: {
    id: 'unit_143rd_signal_battalion',
    name: '143rd Signal Battalion',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_533rd_military_intelligence_battalion: {
    id: 'unit_533rd_military_intelligence_battalion',
    name: '533rd Military Intelligence Battalion',
    type: 'infantry',
    location: 'Frankfurt',
  },
  unit_8th_infantry_division_mechanized: {
    id: 'unit_8th_infantry_division_mechanized',
    name: '8th Infantry Division (Mechanized)',
    type: 'armour',
    location: 'Bad Kreuznach',
  },
  unit_1st_brigade_2: { // Duplicate key: unit_1st_brigade exists
    id: 'unit_1st_brigade_2',
    name: '1st Brigade',
    type: 'armour',
    location: 'Gonsenheim',
  },
  unit_2nd_brigade_2: { // Duplicate key: unit_2nd_brigade exists
    id: 'unit_2nd_brigade_2',
    name: '2nd Brigade',
    type: 'armour',
    location: 'Baumholder',
  },
  unit_3rd_brigade_2: { // Duplicate key: unit_3rd_brigade exists
    id: 'unit_3rd_brigade_2',
    name: '3rd Brigade',
    type: 'armour',
    location: 'Mannheim',
  },
  unit_4th_brigade_aviation_2: { // Duplicate key: unit_4th_brigade_aviation exists
    id: 'unit_4th_brigade_aviation_2',
    name: '4th Brigade (Aviation)',
    type: 'air',
    location: 'Mainz-Finthen',
  },
  unit_8th_infantry_division_artillery: {
    id: 'unit_8th_infantry_division_artillery',
    name: '8th Infantry Division Artillery',
    type: 'artillery',
    location: 'Baumholder',
  },
  unit_8th_infantry_division_support_command: {
    id: 'unit_8th_infantry_division_support_command',
    name: '8th Infantry Division Support Command',
    type: 'infantry',
    location: 'Bad Kreuznach',
  },
  unit_118th_support_battalion: {
    id: 'unit_118th_support_battalion',
    name: '118th Support Battalion',
    type: 'infantry',
    location: 'Mainz',
  },
  unit_202nd_support_battalion: {
    id: 'unit_202nd_support_battalion',
    name: '202nd Support Battalion',
    type: 'infantry',
    location: 'Mannheim',
  },
  unit_208th_support_battalion: {
    id: 'unit_208th_support_battalion',
    name: '208th Support Battalion',
    type: 'infantry',
    location: 'Baumholder',
  },
  unit_708th_support_battalion: {
    id: 'unit_708th_support_battalion',
    name: '708th Support Battalion',
    type: 'infantry',
    location: 'Bad Kreuznach',
  },
  unit_5th_battalion_3rd_air_defense_artillery: {
    id: 'unit_5th_battalion_3rd_air_defense_artillery',
    name: '5th Battalion, 3rd Air Defense Artillery',
    type: 'air',
    location: 'Wackernheim',
  },
  unit_12th_engineer_battalion: {
    id: 'unit_12th_engineer_battalion',
    name: '12th Engineer Battalion',
    type: 'infantry',
    location: 'Dexheim',
  },
  unit_8th_signal_battalion: {
    id: 'unit_8th_signal_battalion',
    name: '8th Signal Battalion',
    type: 'infantry',
    location: 'Bad Kreuznach',
  },
  unit_108th_military_intelligence_battalion: {
    id: 'unit_108th_military_intelligence_battalion',
    name: '108th Military Intelligence Battalion',
    type: 'infantry',
    location: 'Bad Kreuznach',
  },
  unit_7th_personnel_group: {
    id: 'unit_7th_personnel_group',
    name: '7th Personnel Group',
    type: 'infantry',
    location: 'Nellingen auf den Fildern',
  },
  unit_7th_finance_group: {
    id: 'unit_7th_finance_group',
    name: '7th Finance Group',
    type: 'infantry',
    location: 'Stuttgart',
  },
  unit_84th_army_band: {
    id: 'unit_84th_army_band',
    name: '84th Army Band',
    type: 'infantry',
    location: 'Stuttgart',
  },
  unit_5th_battalion_2nd_air_defense_artillery: {
    id: 'unit_5th_battalion_2nd_air_defense_artillery',
    name: '5th Battalion, 2nd Air Defense Artillery',
    type: 'air',
    location: 'Crailsheim',
  },
  unit_11th_aviation_brigade: {
    id: 'unit_11th_aviation_brigade',
    name: '11th Aviation Brigade',
    type: 'air',
    location: 'Illesheim',
  },
  unit_2nd_squadron_6th_cavalry: {
    id: 'unit_2nd_squadron_6th_cavalry',
    name: '2nd Squadron, 6th Cavalry',
    type: 'air',
    location: 'Illesheim',
  },
  unit_4th_battalion_159th_aviation: {
    id: 'unit_4th_battalion_159th_aviation',
    name: '4th Battalion, 159th Aviation',
    type: 'air',
    location: 'Stuttgart',
  },
  unit_4th_battalion_229th_aviation: {
    id: 'unit_4th_battalion_229th_aviation',
    name: '4th Battalion, 229th Aviation',
    type: 'air',
    location: 'Illesheim',
  },
  unit_7th_engineer_brigade: {
    id: 'unit_7th_engineer_brigade',
    name: '7th Engineer Brigade',
    type: 'infantry',
    location: 'Kornwestheim',
  },
  unit_9th_engineer_battalion: {
    id: 'unit_9th_engineer_battalion',
    name: '9th Engineer Battalion',
    type: 'infantry',
    location: 'Aschaffenburg',
  },
  unit_78th_engineer_battalion: {
    id: 'unit_78th_engineer_battalion',
    name: '78th Engineer Battalion',
    type: 'infantry',
    location: 'Ettlingen',
  },
  unit_82nd_engineer_battalion: {
    id: 'unit_82nd_engineer_battalion',
    name: '82nd Engineer Battalion',
    type: 'infantry',
    location: 'Bamberg',
  },
  unit_237th_engineer_battalion: {
    id: 'unit_237th_engineer_battalion',
    name: '237th Engineer Battalion',
    type: 'infantry',
    location: 'Heilbronn',
  },
  unit_565th_engineer_battalion: {
    id: 'unit_565th_engineer_battalion',
    name: '565th Engineer Battalion',
    type: 'infantry',
    location: 'Karlsruhe',
  },
  unit_14th_military_police_brigade: {
    id: 'unit_14th_military_police_brigade',
    name: '14th Military Police Brigade',
    type: 'infantry',
    location: 'Kornwestheim',
  },
  unit_385th_military_police_battalion: {
    id: 'unit_385th_military_police_battalion',
    name: '385th Military Police Battalion',
    type: 'infantry',
    location: 'Kornwestheim',
  },
  unit_793rd_military_police_battalion: {
    id: 'unit_793rd_military_police_battalion',
    name: '793rd Military Police Battalion',
    type: 'infantry',
    location: 'Fürth',
  },
  unit_93rd_signal_brigade: {
    id: 'unit_93rd_signal_brigade',
    name: '93rd Signal Brigade',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_26th_signal_battalion: {
    id: 'unit_26th_signal_battalion',
    name: '26th Signal Battalion',
    type: 'infantry',
    location: 'Heilbronn',
  },
  unit_34th_signal_battalion: {
    id: 'unit_34th_signal_battalion',
    name: '34th Signal Battalion',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_51st_signal_battalion: {
    id: 'unit_51st_signal_battalion',
    name: '51st Signal Battalion',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_207th_military_intelligence_brigade: {
    id: 'unit_207th_military_intelligence_brigade',
    name: '207th Military Intelligence Brigade',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_2nd_military_intelligence_battalion: {
    id: 'unit_2nd_military_intelligence_battalion',
    name: '2nd Military Intelligence Battalion',
    type: 'infantry',
    location: 'Stuttgart',
  },
  unit_307th_military_intelligence_battalion: {
    id: 'unit_307th_military_intelligence_battalion',
    name: '307th Military Intelligence Battalion',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_511th_military_intelligence_battalion: {
    id: 'unit_511th_military_intelligence_battalion',
    name: '511th Military Intelligence Battalion',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_1st_armored_division_2: { // Duplicate key: unit_1st_armoured_division (UK) exists
    id: 'unit_1st_armored_division_2',
    name: '1st Armored Division',
    type: 'armour',
    location: 'Ansbach',
  },
  unit_1st_brigade_3: { // Duplicate key: unit_1st_brigade exists
    id: 'unit_1st_brigade_3',
    name: '1st Brigade',
    type: 'armour',
    location: 'Vilseck',
  },
  unit_2nd_brigade_3: { // Duplicate key: unit_2nd_brigade exists
    id: 'unit_2nd_brigade_3',
    name: '2nd Brigade',
    type: 'armour',
    location: 'Erlangen',
  },
  unit_3rd_brigade_3: { // Duplicate key: unit_3rd_brigade exists
    id: 'unit_3rd_brigade_3',
    name: '3rd Brigade',
    type: 'armour',
    location: 'Bamberg',
  },
  unit_4th_brigade_aviation_3: { // Duplicate key: unit_4th_brigade_aviation exists
    id: 'unit_4th_brigade_aviation_3',
    name: '4th Brigade (Aviation)',
    type: 'air',
    location: 'Katterbach',
  },
  unit_1st_armored_division_artillery: {
    id: 'unit_1st_armored_division_artillery',
    name: '1st Armored Division Artillery',
    type: 'artillery',
    location: 'Zirndorf',
  },
  unit_1st_armored_division_support_command: {
    id: 'unit_1st_armored_division_support_command',
    name: '1st Armored Division Support Command',
    type: 'infantry',
    location: 'Fürth',
  },
  unit_47th_support_battalion: {
    id: 'unit_47th_support_battalion',
    name: '47th Support Battalion',
    type: 'infantry',
    location: 'Erlangen',
  },
  unit_123rd_support_battalion: {
    id: 'unit_123rd_support_battalion',
    name: '123rd Support Battalion',
    type: 'infantry',
    location: 'Fürth',
  },
  unit_125th_support_battalion: {
    id: 'unit_125th_support_battalion',
    name: '125th Support Battalion',
    type: 'infantry',
    location: 'Bamberg',
  },
  unit_501st_support_battalion: {
    id: 'unit_501st_support_battalion',
    name: '501st Support Battalion',
    type: 'infantry',
    location: 'Vilseck',
  },
  unit_6th_battalion_3rd_air_defense_artillery: {
    id: 'unit_6th_battalion_3rd_air_defense_artillery',
    name: '6th Battalion, 3rd Air Defense Artillery',
    type: 'air',
    location: 'Schwabach',
  },
  unit_16th_engineer_battalion: {
    id: 'unit_16th_engineer_battalion',
    name: '16th Engineer Battalion',
    type: 'infantry',
    location: 'Fürth',
  },
  unit_141st_signal_battalion: {
    id: 'unit_141st_signal_battalion',
    name: '141st Signal Battalion',
    type: 'infantry',
    location: 'Ansbach',
  },
  unit_501st_military_intelligence_battalion: {
    id: 'unit_501st_military_intelligence_battalion',
    name: '501st Military Intelligence Battalion',
    type: 'infantry',
    location: 'Ansbach',
  },
  unit_1st_infantry_division_mechanized: {
    id: 'unit_1st_infantry_division_mechanized',
    name: '1st Infantry Division (Mechanized)',
    type: 'armour',
    location: 'Fort Riley, KS',
  },
  unit_1st_infantry_division_forward: {
    id: 'unit_1st_infantry_division_forward',
    name: '1st Infantry Division (Forward)',
    type: 'armour',
    location: 'Göppingen',
  },
  unit_3rd_battalion_34th_armor: {
    id: 'unit_3rd_battalion_34th_armor',
    name: '3rd Battalion, 34th Armor',
    type: 'armour',
    location: 'Böblingen',
  },
  unit_1st_battalion_16th_infantry: {
    id: 'unit_1st_battalion_16th_infantry',
    name: '1st Battalion, 16th Infantry',
    type: 'infantry',
    location: 'Böblingen',
  },
  unit_4th_battalion_16th_infantry: {
    id: 'unit_4th_battalion_16th_infantry',
    name: '4th Battalion, 16th Infantry',
    type: 'infantry',
    location: 'Göppingen',
  },
  unit_2nd_battalion_5th_field_artillery: {
    id: 'unit_2nd_battalion_5th_field_artillery',
    name: '2nd Battalion, 5th Field Artillery',
    type: 'artillery',
    location: 'Neu-Ulm',
  },
  unit_299th_support_battalion: {
    id: 'unit_299th_support_battalion',
    name: '299th Support Battalion',
    type: 'infantry',
    location: 'Göppingen',
  },
  unit_3rd_infantry_division_mechanized: {
    id: 'unit_3rd_infantry_division_mechanized',
    name: '3rd Infantry Division (Mechanized)',
    type: 'armour',
    location: 'Würzburg',
  },
  unit_1st_brigade_4: { // Duplicate key: unit_1st_brigade exists
    id: 'unit_1st_brigade_4',
    name: '1st Brigade',
    type: 'armour',
    location: 'Schweinfurt',
  },
  unit_2nd_brigade_4: { // Duplicate key: unit_2nd_brigade exists
    id: 'unit_2nd_brigade_4',
    name: '2nd Brigade',
    type: 'armour',
    location: 'Kitzingen',
  },
  unit_3rd_brigade_4: { // Duplicate key: unit_3rd_brigade exists
    id: 'unit_3rd_brigade_4',
    name: '3rd Brigade',
    type: 'armour',
    location: 'Aschaffenburg',
  },
  unit_4th_brigade_aviation_4: { // Duplicate key: unit_4th_brigade_aviation exists
    id: 'unit_4th_brigade_aviation_4',
    name: '4th Brigade (Aviation)',
    type: 'air',
    location: 'Giebelstadt',
  },
  unit_3rd_infantry_division_artillery: {
    id: 'unit_3rd_infantry_division_artillery',
    name: '3rd Infantry Division Artillery',
    type: 'artillery',
    location: 'Würzburg',
  },
  unit_3rd_infantry_division_support_command: {
    id: 'unit_3rd_infantry_division_support_command',
    name: '3rd Infantry Division Support Command',
    type: 'infantry',
    location: 'Würzburg',
  },
  unit_3rd_support_battalion: {
    id: 'unit_3rd_support_battalion',
    name: '3rd Support Battalion',
    type: 'infantry',
    location: 'Schweinfurt',
  },
  unit_26th_support_battalion: {
    id: 'unit_26th_support_battalion',
    name: '26th Support Battalion',
    type: 'infantry',
    location: 'Aschaffenburg',
  },
  unit_203rd_support_battalion: {
    id: 'unit_203rd_support_battalion',
    name: '203rd Support Battalion',
    type: 'infantry',
    location: 'Kitzingen',
  },
  unit_703rd_support_battalion: {
    id: 'unit_703rd_support_battalion',
    name: '703rd Support Battalion',
    type: 'infantry',
    location: 'Würzburg',
  },
  unit_4th_battalion_3rd_air_defense_artillery: {
    id: 'unit_4th_battalion_3rd_air_defense_artillery',
    name: '4th Battalion, 3rd Air Defense Artillery',
    type: 'air',
    location: 'Kitzingen',
  },
  unit_10th_engineer_battalion: {
    id: 'unit_10th_engineer_battalion',
    name: '10th Engineer Battalion',
    type: 'infantry',
    location: 'Kitzingen',
  },
  unit_123rd_signal_battalion: {
    id: 'unit_123rd_signal_battalion',
    name: '123rd Signal Battalion',
    type: 'infantry',
    location: 'Würzburg',
  },
  unit_103rd_military_intelligence_battalion: {
    id: 'unit_103rd_military_intelligence_battalion',
    name: '103rd Military Intelligence Battalion',
    type: 'infantry',
    location: 'Würzburg',
  },
  unit_2nd_armored_cavalry: {
    id: 'unit_2nd_armored_cavalry',
    name: '2nd Armored Cavalry',
    type: 'armour',
    location: 'Nuremberg',
  },
  unit_1_2nd_armored_cavalry_squadron: {
    id: 'unit_1_2nd_armored_cavalry_squadron',
    name: '1-2nd Armored Cavalry Squadron',
    type: 'armour',
    location: 'Bindlach',
  },
  unit_2_2nd_armored_cavalry_squadron: {
    id: 'unit_2_2nd_armored_cavalry_squadron',
    name: '2-2nd Armored Cavalry Squadron',
    type: 'armour',
    location: 'Bamberg',
  },
  unit_3_2nd_armored_cavalry_squadron: {
    id: 'unit_3_2nd_armored_cavalry_squadron',
    name: '3-2nd Armored Cavalry Squadron',
    type: 'armour',
    location: 'Amberg',
  },
  unit_4_2nd_air_cavalry_squadron: {
    id: 'unit_4_2nd_air_cavalry_squadron',
    name: '4-2nd Air Cavalry Squadron',
    type: 'air',
    location: 'Feucht',
  },
  vii_corps_artillery: {
    id: 'vii_corps_artillery',
    name: 'VII Corps Artillery',
    type: 'artillery',
    location: 'Augsburg',
  },
  unit_17th_field_artillery_brigade: {
    id: 'unit_17th_field_artillery_brigade',
    name: '17th Field Artillery Brigade',
    type: 'artillery',
    location: 'Augsburg',
  },
  unit_4th_battalion_12th_field_artillery: {
    id: 'unit_4th_battalion_12th_field_artillery',
    name: '4th Battalion, 12th Field Artillery',
    type: 'artillery',
    location: 'Crailsheim',
  },
  unit_1st_battalion_18th_field_artillery: {
    id: 'unit_1st_battalion_18th_field_artillery',
    name: '1st Battalion, 18th Field Artillery',
    type: 'artillery',
    location: 'Augsburg',
  },
  unit_1st_battalion_36th_field_artillery: {
    id: 'unit_1st_battalion_36th_field_artillery',
    name: '1st Battalion, 36th Field Artillery',
    type: 'artillery',
    location: 'Augsburg',
  },
  unit_2nd_battalion_77th_field_artillery: {
    id: 'unit_2nd_battalion_77th_field_artillery',
    name: '2nd Battalion, 77th Field Artillery',
    type: 'artillery',
    location: 'Augsburg',
  },
  unit_72nd_field_artillery_brigade: {
    id: 'unit_72nd_field_artillery_brigade',
    name: '72nd Field Artillery Brigade',
    type: 'artillery',
    location: 'Wertheim',
  },
  unit_3rd_battalion_12th_field_artillery: {
    id: 'unit_3rd_battalion_12th_field_artillery',
    name: '3rd Battalion, 12th Field Artillery',
    type: 'artillery',
    location: 'Aschaffenburg',
  },
  unit_2nd_battalion_14th_field_artillery: {
    id: 'unit_2nd_battalion_14th_field_artillery',
    name: '2nd Battalion, 14th Field Artillery',
    type: 'artillery',
    location: 'Bamberg',
  },
  unit_4th_battalion_14th_field_artillery: {
    id: 'unit_4th_battalion_14th_field_artillery',
    name: '4th Battalion, 14th Field Artillery',
    type: 'artillery',
    location: 'Bamberg',
  },
  unit_4th_battalion_27th_field_artillery: {
    id: 'unit_4th_battalion_27th_field_artillery',
    name: '4th Battalion, 27th Field Artillery',
    type: 'artillery',
    location: 'Wertheim',
  },
  unit_3rd_battalion_35th_field_artillery: {
    id: 'unit_3rd_battalion_35th_field_artillery',
    name: '3rd Battalion, 35th Field Artillery',
    type: 'artillery',
    location: 'Wertheim',
  },
  unit_210th_field_artillery_brigade: {
    id: 'unit_210th_field_artillery_brigade',
    name: '210th Field Artillery Brigade',
    type: 'artillery',
    location: 'Herzogenaurach',
  },
  unit_3rd_battalion_5th_field_artillery: {
    id: 'unit_3rd_battalion_5th_field_artillery',
    name: '3rd Battalion, 5th Field Artillery',
    type: 'artillery',
    location: 'Nuremberg',
  },
  unit_2nd_battalion_12th_field_artillery: {
    id: 'unit_2nd_battalion_12th_field_artillery',
    name: '2nd Battalion, 12th Field Artillery',
    type: 'artillery',
    location: 'Herzogenaurach',
  },
  unit_3rd_battalion_17th_field_artillery: {
    id: 'unit_3rd_battalion_17th_field_artillery',
    name: '3rd Battalion, 17th Field Artillery',
    type: 'artillery',
    location: 'Ansbach',
  },
  unit_5th_battalion_17th_field_artillery: {
    id: 'unit_5th_battalion_17th_field_artillery',
    name: '5th Battalion, 17th Field Artillery',
    type: 'artillery',
    location: 'Herzogenaurach',
  },
  unit_2nd_corps_support_command: {
    id: 'unit_2nd_corps_support_command',
    name: '2nd Corps Support Command',
    type: 'infantry',
    location: 'Nellingen auf den Fildern',
  },
  special_troops_battalion: {
    id: 'special_troops_battalion',
    name: 'Special Troops Battalion',
    type: 'infantry',
    location: 'Nellingen auf den Fildern',
  },
  unit_4th_transportation_battalion: {
    id: 'unit_4th_transportation_battalion',
    name: '4th Transportation Battalion',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_7th_battalion_159th_aviation: {
    id: 'unit_7th_battalion_159th_aviation',
    name: '7th Battalion, 159th Aviation',
    type: 'air',
    location: 'Nellingen auf den Fildern',
  },
  unit_101st_ordnance_battalion: {
    id: 'unit_101st_ordnance_battalion',
    name: '101st Ordnance Battalion',
    type: 'infantry',
    location: 'Heilbronn',
  },
  unit_7th_corps_support_group: {
    id: 'unit_7th_corps_support_group',
    name: '7th Corps Support Group',
    type: 'infantry',
    location: 'Crailsheim',
  },
  unit_13th_supply_and_service_battalion: {
    id: 'unit_13th_supply_and_service_battalion',
    name: '13th Supply and Service Battalion',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_1st_maintenance_battalion: {
    id: 'unit_1st_maintenance_battalion',
    name: '1st Maintenance Battalion',
    type: 'infantry',
    location: 'Böblingen',
  },
  unit_71st_maintenance_battalion: {
    id: 'unit_71st_maintenance_battalion',
    name: '71st Maintenance Battalion',
    type: 'infantry',
    location: 'Fürth',
  },
  unit_87th_maintenance_battalion: {
    id: 'unit_87th_maintenance_battalion',
    name: '87th Maintenance Battalion',
    type: 'infantry',
    location: 'Wertheim',
  },
  unit_30th_medical_group: {
    id: 'unit_30th_medical_group',
    name: '30th Medical Group',
    type: 'infantry',
    location: 'Ludwigsburg',
  },
  unit_31st_combat_support_hospital: {
    id: 'unit_31st_combat_support_hospital',
    name: '31st Combat Support Hospital',
    type: 'infantry',
    location: 'Nellingen auf den Fildern',
  },
  unit_67th_evacuation_hospital: {
    id: 'unit_67th_evacuation_hospital',
    name: '67th Evacuation Hospital',
    type: 'infantry',
    location: 'Würzburg',
  },
  unit_128th_combat_support_hospital: {
    id: 'unit_128th_combat_support_hospital',
    name: '128th Combat Support Hospital',
    type: 'infantry',
    location: 'Nellingen auf den Fildern',
  }
};
